# Generated by Django 6.0.2 on 2026-08-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_todo_delete_todomodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
