# Generated by Django 6.0.2 on 2026-08-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_todo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "low"), ("MEDIUM", "medium"), ("HIGH", "high")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
    ]
