# Generated by Django 6.0.2 on 2026-08-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_todo_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
